//
//  BalsameeDoctorApp
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <XCTest/XCTest.h>
#import "PatientsController.h"
#import "TestHelper.h"
#import "TestBaseController.h"

@interface  TestPatientsController : TestBaseController
//Controller instance for all tests
@property PatientsController* controller;
@end 


@implementation  TestPatientsController : TestBaseController

//Setup test class
//This method is called before the invocation of each test method in the test class
- (void)setUp {
    [super setUp];
    self.controller = [[PatientsController alloc]init];
}

//Teardown test class
//This method is called after the invocation of each test method in the test class
- (void)tearDown {
    [super tearDown];
}	


// TODO: Add Description    
-(void) testShowPatientsList {
    //Set up test expectations
    XCTestExpectation *expectation =[self expectationWithDescription:@"High Expectations"];
    // Parameters for the API call
    NSString* xAuthenticationToken = @"{{token}}";
    NSString* xSessionId = @"{{session_id}}";
    NSString* xAppId = @"doctor_app";

    // Set callback and perform API call
    [self.controller getShowPatientsListAsyncWithXAuthenticationToken: xAuthenticationToken xSessionId : xSessionId xAppId : xAppId  completionBlock:^(BOOL success, HttpContext* context, NSError* error) { 
       // Test response code
        XCTAssertEqual(200, context.response.statusCode);
        

        [expectation fulfill];
    }];
    [self wait];
}



@end
