//
//  BalsameeDoctorApp
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <XCTest/XCTest.h>
#import "DoctorInformationsController.h"
#import "TestHelper.h"
#import "TestBaseController.h"

@interface  TestDoctorInformationsController : TestBaseController
//Controller instance for all tests
@property DoctorInformationsController* controller;
@end 


@implementation  TestDoctorInformationsController : TestBaseController

//Setup test class
//This method is called before the invocation of each test method in the test class
- (void)setUp {
    [super setUp];
    self.controller = [[DoctorInformationsController alloc]init];
}

//Teardown test class
//This method is called after the invocation of each test method in the test class
- (void)tearDown {
    [super tearDown];
}	


// TODO: Add Description    
-(void) testUpdateDoctorInfo {
    //Set up test expectations
    XCTestExpectation *expectation =[self expectationWithDescription:@"High Expectations"];
    // Parameters for the API call
    NSString* xAuthenticationToken = @"{{token}}";
    NSString* xSessionId = @"{{session_id}}";
    NSString* xAppId = @"doctor_app";
    NSString* doctorInformationLatitude = @"30.0500";
    NSString* doctorInformationLongitude = @"31.2333";
    NSString* doctorInformationIsVideoAvailable = @"true";
    NSString* doctorInformationIsAvailable = @"true";

    // Set callback and perform API call
    [self.controller updateDoctorInfoAsyncWithXAuthenticationToken: xAuthenticationToken xSessionId : xSessionId xAppId : xAppId doctorInformationLatitude : doctorInformationLatitude doctorInformationLongitude : doctorInformationLongitude doctorInformationIsVideoAvailable : doctorInformationIsVideoAvailable doctorInformationIsAvailable : doctorInformationIsAvailable  completionBlock:^(BOOL success, HttpContext* context, NSError* error) { 
       // Test response code
        XCTAssertEqual(200, context.response.statusCode);
        

        [expectation fulfill];
    }];
    [self wait];
}



@end
