//
//  BalsameeDoctorApp
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_RESERVATIONREQUEST
#define APIMATIC_RESERVATIONREQUEST

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "Individual.h"


//protocol defined for deserialization of JSON
@protocol ReservationRequest
@end

@interface ReservationRequest : JSONModel

/**
* TODO: Write general description for this field
*/
@property int mid;

/**
* TODO: Write general description for this field
*/
@property NSString* address;

/**
* TODO: Write general description for this field
*/
@property NSString* addressDetails;

/**
* TODO: Write general description for this field
*/
@property NSString* mobileNumber;

/**
* TODO: Write general description for this field
*/
@property NSString* currentStatus;

/**
* TODO: Write general description for this field
*/
@property double patientLatitude;

/**
* TODO: Write general description for this field
*/
@property double patientLongitude;

/**
* TODO: Write general description for this field
*/
@property BOOL createdByCrm;

/**
* TODO: Write general description for this field
*/
@property Individual* individual;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif