//
//  BalsameeDoctorApp
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "ReservationRequest.h"

@implementation ReservationRequest

/**
* TODO: Write general description for this method
*/
@synthesize mid;

/**
* TODO: Write general description for this method
*/
@synthesize address;

/**
* TODO: Write general description for this method
*/
@synthesize addressDetails;

/**
* TODO: Write general description for this method
*/
@synthesize mobileNumber;

/**
* TODO: Write general description for this method
*/
@synthesize currentStatus;

/**
* TODO: Write general description for this method
*/
@synthesize patientLatitude;

/**
* TODO: Write general description for this method
*/
@synthesize patientLongitude;

/**
* TODO: Write general description for this method
*/
@synthesize createdByCrm;

/**
* TODO: Write general description for this method
*/
@synthesize individual;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"id": @"mid",
        @"address": @"address",
        @"address_details": @"addressDetails",
        @"mobile_number": @"mobileNumber",
        @"current_status": @"currentStatus",
        @"patient_latitude": @"patientLatitude",
        @"patient_longitude": @"patientLongitude",
        @"created_by_crm": @"createdByCrm",
        @"individual": @"individual"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end