//
//  BalsameeDoctorApp
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef BalsameeDoctorApp_Configuration_h
#define BalsameeDoctorApp_Configuration_h

/** The base Uri for API calls */
extern NSString* Configuration_BaseUri;

#endif
