//
//  BalsameeDoctorApp
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface DoctorInformationsController : BaseController

/**
* Completion block definition for asynchronous call to Get Doctor Information */
typedef void (^CompletedGetDoctorInformation)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
*/
- (void) getDoctorInformationWithCompletionBlock:(CompletedGetDoctorInformation) onCompleted;

/**
* Completion block definition for asynchronous call to Update Doctor Info */
typedef void (^CompletedPutUpdateDoctorInfo)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    xAppId    Required parameter: Example: 
* @param    doctorInformationLatitude    Required parameter: Example: 
* @param    doctorInformationLongitude    Required parameter: Example: 
* @param    doctorInformationIsVideoAvailable    Required parameter: Example: 
* @param    doctorInformationIsAvailable    Required parameter: Example: 
*/
- (void) updateDoctorInfoAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                xAppId:(NSString*) xAppId
                doctorInformationLatitude:(NSString*) doctorInformationLatitude
                doctorInformationLongitude:(NSString*) doctorInformationLongitude
                doctorInformationIsVideoAvailable:(NSString*) doctorInformationIsVideoAvailable
                doctorInformationIsAvailable:(NSString*) doctorInformationIsAvailable
                completionBlock:(CompletedPutUpdateDoctorInfo) onCompleted;

@end