//
//  BalsameeDoctorApp
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "NSDate+extension.h"

@interface GeneralController : BaseController

/**
* Completion block definition for asynchronous call to Get App Version */
typedef void (^CompletedGetAppVersion)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    appVersion    Required parameter: Example: 
* @param    xAppId    Required parameter: Example: 
*/
- (void) getAppVersionAsyncWithAppVersion:(NSDate*) appVersion
                xAppId:(NSString*) xAppId
                completionBlock:(CompletedGetAppVersion) onCompleted;

@end