//
//  BalsameeDoctorApp
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "ReservationRequestsJson.h"

@interface ReservationRequestsController : BaseController

/**
* Completion block definition for asynchronous call to List Reservation Request */
typedef void (^CompletedGetListReservationRequest)(BOOL success, HttpContext* context, ReservationRequestsJson* response, NSError* error);

/**
* Doctor reject resesrvation request
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    xAppId    Required parameter: Example: 
*/
- (void) listReservationRequestAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                xAppId:(NSString*) xAppId
                completionBlock:(CompletedGetListReservationRequest) onCompleted;

/**
* Completion block definition for asynchronous call to Create Reservation Request */
typedef void (^CompletedPostCreateReservationRequest)(BOOL success, HttpContext* context, NSError* error);

/**
* URL: /api/v5/reservation_requests  
* Method: POST  
* @param doctor_id  
* @param address  
* @param address_details  
* @param mobile_number  
* @param patient_latitude  
* @param patient_longitude  
* @param [Header] X-Authentication-Token  
* @param [Header] X-Session-Id  
* @param [Header] X-App-Id  
* @return [JsonArray]  errors  ( code: 422 )  
* @return [JsonObject] success ( code: 200 )  
* * [Header] X-App-Id = doctor_app used to indicate that the request is sent from doctor app  
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    xAppId    Required parameter: Example: 
* @param    doctorId    Required parameter: Example: 
* @param    address    Required parameter: Example: 
* @param    addressDetails    Required parameter: Example: 
* @param    mobileNumber    Required parameter: Example: 
* @param    patientLatitude    Required parameter: Example: 
* @param    patientLongitude    Required parameter: Example: 
*/
- (void) createReservationRequestAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                xAppId:(NSString*) xAppId
                doctorId:(NSString*) doctorId
                address:(NSString*) address
                addressDetails:(NSString*) addressDetails
                mobileNumber:(NSString*) mobileNumber
                patientLatitude:(NSString*) patientLatitude
                patientLongitude:(NSString*) patientLongitude
                completionBlock:(CompletedPostCreateReservationRequest) onCompleted;

/**
* Completion block definition for asynchronous call to Update Reservation Request */
typedef void (^CompletedPutUpdateReservationRequest)(BOOL success, HttpContext* context, NSError* error);

/**
* URL: /api/v5/reservation_requests/:reservation_request_id  
* Method: PUT  
* @param current_status  
* @param [Header] X-Authentication-Token  
* @param [Header] X-Session-Id  
* @param [Header] X-App-Id  
* @return [JsonArray]  errors  ( code: 422 )  
* @return [JsonObject] success ( code: 200 )  
* * [Header] X-App-Id = doctor_app used to indicate that the request is sent from doctor app  
* * This request can be used to accept, reject, cancel or complete a reservation request using:  
*  * current_status can be one of the following  
*  accepted, rejected, canceled, completed
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    xAppId    Required parameter: Example: 
* @param    currentStatus    Required parameter: Example: 
*/
- (void) updateReservationRequestAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                xAppId:(NSString*) xAppId
                currentStatus:(NSString*) currentStatus
                completionBlock:(CompletedPutUpdateReservationRequest) onCompleted;

/**
* Completion block definition for asynchronous call to Index Reservation Request */
typedef void (^CompletedGetIndexReservationRequest)(BOOL success, HttpContext* context, NSError* error);

/**
* URL: /api/v5/reservation_requests  
* Method: GET  
* @param status  
* @param [Header] X-Authentication-Token  
* @param [Header] X-Session-Id  
* @param [Header] X-App-Id  
* @return [JsonArray]  errors  ( code: 422 )  
* @return [JsonObject] success ( code: 200 )  
* * [Header] X-App-Id = doctor_app used to indicate that the request is sent from doctor app  
* * params[status] can be  used to list reservation request with the given statuses  
*  * status can be a comma ',' separated lis of the following  
*  accepted,rejected,canceled,completed  
* * params[status] can be ignored to list all reservation request
* @param    status    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    xAppId    Required parameter: Example: 
*/
- (void) getIndexReservationRequestAsyncWithStatus:(NSString*) status
                xAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                xAppId:(NSString*) xAppId
                completionBlock:(CompletedGetIndexReservationRequest) onCompleted;

/**
* Completion block definition for asynchronous call to Reject Order */
typedef void (^CompletedPutRejectOrder)(BOOL success, HttpContext* context, NSError* error);

/**
* Doctor reject resesrvation request
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    xAppId    Required parameter: Example: 
* @param    currentStatus    Required parameter: Example: 
*/
- (void) updateRejectOrderAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                xAppId:(NSString*) xAppId
                currentStatus:(NSString*) currentStatus
                completionBlock:(CompletedPutRejectOrder) onCompleted;

/**
* Completion block definition for asynchronous call to Show Reservation Request */
typedef void (^CompletedGetShowReservationRequest)(BOOL success, HttpContext* context, NSError* error);

/**
* URL: /api/v5/reservation_requests/:reservation_request_id  
* Method: GET  
* @param [Header] X-Authentication-Token  
* @param [Header] X-Session-Id  
* @param [Header] X-App-Id  
* @return [JsonArray]  errors  ( code: 422 )  
* @return [JsonObject] success ( code: 200 )  
* * [Header] X-App-Id = doctor_app used to indicate that the request is sent from doctor app  
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    xAppId    Required parameter: Example: 
*/
- (void) getShowReservationRequestAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                xAppId:(NSString*) xAppId
                completionBlock:(CompletedGetShowReservationRequest) onCompleted;

@end