//
//  BalsameeDoctorApp
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface SessionsController : BaseController

/**
* Completion block definition for asynchronous call to Log Out */
typedef void (^CompletedPutLogOut)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    xAppId    Required parameter: Example: 
* @param    doctorInformationIsAvailable    Required parameter: Example: 
* @param    doctorInformationLang    Required parameter: Example: 
* @param    doctorInformationLatitude    Required parameter: Example: 
* @param    doctorInformationLongitude    Required parameter: Example: 
*/
- (void) updateLogOutAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                xAppId:(NSString*) xAppId
                doctorInformationIsAvailable:(NSString*) doctorInformationIsAvailable
                doctorInformationLang:(NSString*) doctorInformationLang
                doctorInformationLatitude:(NSString*) doctorInformationLatitude
                doctorInformationLongitude:(NSString*) doctorInformationLongitude
                completionBlock:(CompletedPutLogOut) onCompleted;

/**
* Completion block definition for asynchronous call to logout */
typedef void (^CompletedDeleteLogout)(BOOL success, HttpContext* context, NSError* error);

/**
* Doctor App log out
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
*/
- (void) deleteLogoutAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                completionBlock:(CompletedDeleteLogout) onCompleted;

/**
* Completion block definition for asynchronous call to Save Session device token */
typedef void (^CompletedPutSaveSessionDeviceToken)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    deviceToken    Required parameter: Example: 
*/
- (void) updateSaveSessionDeviceTokenAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                deviceToken:(NSString*) deviceToken
                completionBlock:(CompletedPutSaveSessionDeviceToken) onCompleted;

/**
* Completion block definition for asynchronous call to Get user details */
typedef void (^CompletedGetUserDetails)(BOOL success, HttpContext* context, NSError* error);

/**
* Get individual with more details 
* 1 - reservation_request
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
*/
- (void) getUserDetailsAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                completionBlock:(CompletedGetUserDetails) onCompleted;

@end